name: Deploy documentation

on:
  push:
    branches:
      - main

jobs:
  deploy-doc:
    name: Deploy API doc on Bump
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: '18.x'
      - name: Install node dependencies
        run: npm install
      - name: Generate OpenAPI contract
        run: node contract.js > doc/api-definition.yml
      - name: Deploy API documentation
        uses: bump-sh/github-action@v1
        with:
          doc: express-oas-example
          token: ${{secrets.BUMP_TOKEN}}
          file: doc/api-definition.yml
