name: Bump Version and Deploy

on:
  push:
    branches: [ main ]

jobs:
  bump-version:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'skip ci')"

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT }}
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          
      - name: Configure Git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
      - name: Get current version
        run: |
          CURRENT_VERSION=$(node -p "require('./package.json').version")
          echo "CURRENT_VERSION=$CURRENT_VERSION" >> $GITHUB_ENV
          
      - name: Bump version if needed
        run: |
          if ! git rev-parse "v$CURRENT_VERSION" >/dev/null 2>&1; then
            npm version patch -m "Bump version to %s [skip ci]"
          else
            echo "Version v$CURRENT_VERSION already exists, skipping version bump"
          fi
          
      - name: Push changes
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git push --follow-tags
          else
            echo "No changes to push"
          fi
